<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.actforever</groupId>
        <artifactId>kuudra</artifactId>
        <version>v0.4.0-alpha-3</version>
    </parent>
    <artifactId>kuudra-app</artifactId>
    <dependencies>
        <dependency>
            <groupId>io.github.actforever</groupId>
            <artifactId>kuudra-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.actforever</groupId>
            <artifactId>kuudra-runtime</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.actforever</groupId>
            <artifactId>kuudra-config</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.actforever</groupId>
            <artifactId>kuudra-plugin</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.actforever</groupId>
            <artifactId>kuudra-logging</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
