<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>io.github.actforever</groupId><artifactId>kuudra</artifactId><version>0.1.0-SNAPSHOT</version></parent>
    <artifactId>kuudra-app</artifactId>
    <dependencies>
        <dependency><groupId>io.github.actforever</groupId><artifactId>kuudra-runtime</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>io.github.actforever</groupId><artifactId>kuudra-config</artifactId><version>${project.version}</version></dependency>
    </dependencies>
</project>
