spring:
  application:
    name: kuudra-web
server:
  port: 8080
kuudra:
  config:
    path: ${KUUDRA_CONFIG_PATH:}
knife4j:
  enable: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /doc.html
