spring:
  application:
    name: kuudra-web
server:
  port: 8080

knife4j:
  enable: true
  setting:
    enable-group: true
    language: zh_cn
springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    urls-primary-name: all
    tags-sorter: alpha
    operations-sorter: alpha
  group-configs:
    - group: all
      paths-to-match:
        - /api/v1/**
      packages-to-scan: io.github.actforever.kuudra.web.controller
    - group: app
      paths-to-match: /api/v1/app/**
      packages-to-scan: io.github.actforever.kuudra.web.controller
    - group: resource-documentation
      paths-to-match: /api/v1/resource-documentation/**
      packages-to-scan: io.github.actforever.kuudra.web.controller
    - group: runtime
      paths-to-match: /api/v1/runtime/**
      packages-to-scan: io.github.actforever.kuudra.web.controller
    - group: system-events
      paths-to-match: /api/v1/system-events/**
      packages-to-scan: io.github.actforever.kuudra.web.controller
    - group: plugin
      paths-to-match: /api/v1/plugin/**
      packages-to-scan: io.github.actforever.kuudra.web.controller
