# Lowest-priority Kuudra App configuration.
home-directory: .kuudra

runtime:
  queue-capacity: 1024
  worker-threads: 2

plugins:
  directories:
    - .kuudra/plugins
  home-directory: .kuudra/plugins
  load: []

flows-directory: flows
global-context: {}
